### PR TITLE
Proposal: Migrating from server rendered jsps

### PR DESCRIPTION
**Pull request by internettrans**
I'd love to hear a lot from PIH and other distributions that rely on ref app and JSPs a lot.

@dkayiwa @djazayeri @mogoodrich @brandones

This PR will remain open for a while for discussion. Merging happens if/when the following three people approve: @fatmali @brandones @angshu

### CODE REVIEW

**Comment by internettrans** [comment]
Oh also @mseaton, I'd like to hear your thoughts on this one.

**Comment by mseaton** [comment]
This all seems reasonable to me @joeldenning .

**Comment by mogoodrich** [comment]
I agree with @mseaton , seems reasonable...

**Comment by djazayeri** [comment]
Looks reasonable to me also.

**Comment by internettrans** [comment]
@fatmali @angshu @ojwanganto Could you take a look at this and either comment or approve? To approve, you can add your Thumbs Up emoji, make a github comment saying you approve, or doing a real Github approval review if you have permissions to do so.

**Comment by internettrans** [comment]
I'm waiting on 3 core team members approving this before merging. We already have one from @brandones

**Review by fatmali — APPROVED** [review]

**Comment by internettrans** [comment]
3 core team approvals -- merging now.

**Pull request merged**
