### PR TITLE
Proposal: Styleguide Javascript Components

### PR DESCRIPTION
**Pull request by internettrans**
This one is the proposal I feel maybe the most conflicted about. Important decisions to make, and none of the options feel perfect.

### CODE REVIEW

**Comment by internettrans** [comment]
Will merge if/when there are three approvals from @fatmali @angshu @ojwanganto, @brandones

**Comment by internettrans** [comment]
Regarding *how* (but not whether) to implement web components, I tweeted a poll that stirred some interesting and potentially informative discussion: https://twitter.com/Joelbdenning/status/1137052045926469632

**Comment by mseaton** [comment]
FYI - I think this proposal looks great

**Comment by ojwanganto** [comment]
I approve this proposal

**Comment by fatmali** [comment]
Hi @joeldenning this looks great. The only downside is having to learn a new tool (stenciljs) in the process but that's alright. I approve.

**Comment by internettrans** [comment]
I am closing https://github.com/openmrs/openmrs-rfc-frontend/pull/9 because I no longer believe web components to be the best option for OpenMRS. Instead, I’ll replace it with a new PR that proposes a css-first styleguide with javascript components being framework specific and secondary in importance to the css itself.

Reasons for it will be explained in more detail in the new RFC proposal.

**Comment by dkayiwa** [comment]
@joeldenning i anxiously look forward to the explanation! Just for learning purposes. 😊

**Pull request closed without merging**
